driver_approved_virtual_traffic_light_node:
  ros__parameters:
    driver_input_topic: "/raptor_dbw_interface/driver_input_report"
    virtual_traffic_light_state_topic: "/awapi/tmp/virtual_traffic_light_states"
    virtual_traffic_light_type: "virtual"
    virtual_traffic_light_id: "99"
    approval_duration_sec: 5.0
    publish_rate_hz: 10.0
    is_finalized: false
